### ISSUE TITLE
[Bug] Throws an error when selecting "All Stocks" (default) option for index screening

### ISSUE THREAD

**Issue by dummifiedme** [pranjal-joshi/Screeni-py#109]
Throws this error when going with default option
![image](https://user-images.githubusercontent.com/68785729/154421080-44e8d3be-323f-4f9e-8949-ce6742201177.png)

Note: If we select anything other than that, the code seems to work fine :)

**Comment by pranjal-joshi** [comment]
Please try to run the code after 3.30 PM and let me know if it shows the same error.
Your Network/ISP may have restricted access to Yahoo finance API which is used between 9.15 AM to 3.30 PM.
Running script after 3.30/4 PM uses EoD data generated by Screenipy cloud.

**Comment by pranjal-joshi** [comment]
Also, Are you working behind any network proxy? It may restrict the software to reach the servers.
It's the usual cause of this error because if you're using it on the computer provided by the organization, they might have configured it as a measure of cyber security. So, suggest using it on a personal PC without any proxy.

**Comment by pranjal-joshi** [comment]
> I checked just now, and still the same error.
> 
> Is there a diagnostic check that I can do to pin point the problem?

For the time being, you have to clone the repo, set up the dependency requirements, and modified the code to check what's wrong.
However, I will try to add a debug logging feature in the next feature.

As a workaround, you can `wine` on Linux to run `screenipy.exe` rather than `bin` file. Give it a try and keep me posted.

**Comment by pranjal-joshi** [comment]
@dummifiedme 

Have you got it working? Otherwise try downloading the latest release from the homepage.
