### ISSUE TITLE
 Intraday Live Scanner

### ISSUE THREAD

**Issue by sumancology** [pranjal-joshi/Screeni-py#156]
Hello,

Thank you for the good  and exceptional work. 

I tried the  Intraday Live Scanner ie, Option `E`.  The output always comes out empty with the 60sec update cycle (see below). Could you verify that this is not the case and that I am doing something wrong.  Thanks.

OUTPUT

[+] 5-EMA : Live Intraday Scanner 	Last Scanned: 14:26:30
+--------+---------------+----------+------+----------+-------+
| Time   | Stock/Index   | Action   | SL   | Target   | R:R   |
|--------+---------------+----------+------+----------+-------|
+--------+---------------+----------+------+----------+-------+

[+] 5-EMA : Live Intraday Scanner 	Last Scanned: 14:26:30
+--------+---------------+----------+------+----------+-------+
| Time   | Stock/Index   | Action   | SL   | Target   | R:R   |
|--------+---------------+----------+------+----------+-------|
+--------+---------------+----------+------+----------+-------+

**Comment by pranjal-joshi** [comment]
Hi @sumancology 

Live scanner will display 5-EMA based entries for Nifty and BankNifty whenever the conditions occur in real time.
Unless the conditions occur, the results will be empty and that's why it keeps scanning the markets periodically.

Here is an example for your reference.

![Screenshot 2022-12-02 at 12.46.01 PM.png](https://user-images.githubusercontent.com/6128978/216503326-b2668e85-8367-4949-92ef-a88018a828f3.png)

**Comment by sumancology** [comment]
> Hi @sumancology
> 
> Live scanner will display 5-EMA based entries for Nifty and BankNifty whenever the conditions occur in real time. Unless the conditions occur, the results will be empty and that's why it keeps scanning the markets periodically.
> 
> Here is an example for your reference.
> 
> ![Screenshot 2022-12-02 at 12.46.01 PM.png](https://user-images.githubusercontent.com/6128978/216503326-b2668e85-8367-4949-92ef-a88018a828f3.png)

Hello,
Thank you for the quick response.  The issue is resolved. 

Appreciated.
