### ISSUE TITLE
Stuck after stock Screening

### ISSUE THREAD

**Issue by sunel** [pranjal-joshi/Screeni-py#78]
**Describe the bug**
While screening its stuck at the last and not showing the results 

**To Reproduce**
Defualt > 6 > 1

**Screenshots**
![image](https://user-images.githubusercontent.com/1009777/148767001-12d9e873-cef6-4f0e-bf78-90a06b79a5b1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: v1.28

**Comment by pranjal-joshi** [comment]
Hello @sunel 

1. Does this always happens when you choose `Option > 6 > 1`?
2. If this occurs randomly for all options, how frequently does it happen?
3. If you press `Ctrl+C`, when it is stuck, does it shows the result table or exit/throw some error?

Sometimes when the Yahoo Finance API fails to deliver the data of any of the stock then this may occur.

**Comment by sunel** [comment]
>Does this always happens when you choose `Option > 6 > 1`?

Yes

>If you press Ctrl+C, when it is stuck, does it shows the result table or exit/throw some error?

 it shows the result table

**Comment by pranjal-joshi** [comment]
@sunel 
Can you try `Option > 6 > 1` for various indices rather than for all stocks and post your results?
There might be some inconsistencies with the newly listed stocks which the backend API is not able to handle properly.

**Comment by sunel** [comment]
Yes this seems to working
